name: Build Flipper Application Package

on:
  push:
    tags:
      - "v**"
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout application repository
        uses: actions/checkout@v3
      - name: Get app ID
        id: app-id
        run: echo "APP_ID=$(grep appid application.fam | awk -F '=' '{print $2}' | tr -d '\",')" >> $GITHUB_OUTPUT
      - name: Cache build folder
        uses: actions/cache@v3
        with:
          path: build
          key: build
      - name: Build FAPs
        run: make build
      - name: Upload FAP artifact
        uses: actions/upload-artifact@v3
        with:
          name: flipper-application-package
          path: build/${{ steps.app-id.outputs.APP_ID }}.fap
          if-no-files-found: error
